#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

$app = new Symfony\Component\Console\Application('PrestaShop Installer', '1.0.0');
$app->add(new PrestaShop\Installer\Console\NewCommand());

$app->run();
